# 1. S3 Bucket for archival data only.
# 2. SNS Topic for notification of archive retrieval job completion.

# Please refer bucket policy. User should upload with storage class set as GLACIER.
# If not GLACIER, request will be denied.

# User can upload as belows using AWS CLI.
# aws s3 cp FILENAME s3://glacier-example-bucket/ --storage-class GLACIER

Resources:
  S3ForGlacier:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: glacier-example-bucket

      # Lifecycle rule for new objects in this bucket. This rule changes object's Storage Class to GLACIER after its creation.
      # (Actually this Lifecycle is meaningless due to bucket policy. User can't create non-GLACIER object in this bucket)
      LifecycleConfiguration:
        Rules:
        - Id: DefaultAsGlacier
          Status: Enabled
          Transitions:
          - TransitionInDays: 0
            StorageClass: GLACIER
      
      # Set notification for Archive retrieval completion.
      # Because GLACIER don't show you any progress regarding archive retrieval job, it's helpful if set notification.
      # User can get notification when archive retrieval complete
      NotificationConfiguration:
        TopicConfigurations:
        - Event: s3:ObjectRestore:Completed
          Topic: !Ref SNSForGlacier

  S3ForGlacierPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3ForGlacier
      PolicyDocument:
        Statement:
        # ... some rule
        # ... some rule

        # By setting bucket policy as below, User can't request to store non-GLACIER objects.
        - Sid: "Deny other storage class upload"
          Action: ["s3:PutObject"]
          Effect: "Deny"
          Resource:
          - "arn:aws:s3:::glacier-example-bucket/*"
          Principal: "*"
          Condition:
            StringNotLike:
              "s3:x-amz-storage-class":
              - "GLACIER"

  # SNS Topic for notification of Retrieval job completion.
  SNSForGlacier:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: glacier-example-bucket
      Subscription:
        - Endpoint: my-email-address@example.com
          Protocol: email
  
  # SNS Topic policy which allows S3 bucket to publish notification
  SNSForGlacierPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
      - !Ref SNSForGlacier
      PolicyDocument:
        Statement:
        - Sid: "Allow Publish from S3"
          Effect: "Allow"
          Principal:
            Service:
            - s3.amazonaws.com
          Action: ["sns:Publish"]
          Resource:
          - !Ref SNSForGlacier
          Condition:
            ArnLike:
              "aws:SourceArn":
              - "arn:aws:s3:::glacier-example-bucket"
