# Simple S3 Bucket with Bucket Policy
# Bucket Policy has two statements.
# Statement 1 : Allows public access "GetObject" from specific IP addresses only.
# Statement 2 : PutObject, DeleteObject, and ListBucket is only allowed from specific IAM Role.
#
# Use case : Allow public access to this bucket from specific users with fixed IP. Put, Delete Object and Listing bucket are only allowed from EC2 instances with specific IAM Role.
#
# Replace the AWS:SourceIp part IP to specific IP you want to allow in BucketPolicy Statement attribute
# And For IAM Role, put your account number and IAM Role name.

AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-simple-s3-bucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
        - Sid: "Allow GetObject from specific IPs only"
          Action:
          - "s3:GetObject"
          Effect: "Allow"
          Resource:
          - "arn:aws:s3:::my-simple-s3-bucket/*"
          Principal: "*"
          Condition:
            IpAddress:
              "aws:SourceIp":
              - "8.8.8.8/32" # Example IP
              - "1.2.3.4/32" # Example IP
        - Sid: "Allow Get,Put Object and ListBucket from specific IAM Role only"
          Action: ["s3:GetObject", "s3:PutObject", "s3:DeleteObject", "s3:ListBucket"]
          Effect: "Allow"
          Resource:
          - "arn:aws:s3:::my-simple-s3-bucket" # For ListBucket
          - "arn:aws:s3:::my-simple-s3-bucket/*" # For Get,Put,Delete Object
          Principal:
            AWS:
            - "arn:aws:iam::YOUR-AWS-ACCOUNT-NUMBER:role/IAM-ROLE-NAME"
